/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewLayer;

import BussinesModelLayer.Farmacia;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;



/**
 *
 * @author zerme
 */
public class frmFarmacias extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFarmacias
     */
    public frmFarmacias() {
        initComponents();
        btnMostrarProductos.setVisible(false);
        tblFarmacias.setModel(new Farmacia().GetAllModel());
        new TableDesing().desingOfTable(tblFarmacias);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnActualizar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrarProductos = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        tblFarmacias = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Farmacias");
        setVisible(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnActualizar.setText("Actualizar");
        btnActualizar.setFocusable(false);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnActualizar);

        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNuevo);

        btnModificar.setText("Modificar");
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnModificar);

        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnMostrarProductos.setText("Mostrar Productos");
        btnMostrarProductos.setFocusable(false);
        btnMostrarProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrarProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMostrarProductos);

        tblFarmacias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFarmacias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFarmaciasMouseClicked(evt);
            }
        });
        scroll.setViewportView(tblFarmacias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (tblFarmacias.getSelectedRow()>= 0) {
            int idFarmacia = (int) tblFarmacias.getValueAt(tblFarmacias.getSelectedRow(), 0);
            Farmacia farmacia = new Farmacia();
            farmacia.setIdFarmacia(idFarmacia);
            if(farmacia.Delete()){
                JOptionPane.showMessageDialog(rootPane, "Farmacia eliminada correctamente");
            }else {
                JOptionPane.showMessageDialog(rootPane, "No ha sido posible eliminar la farmacia");
            }
            tblFarmacias.setModel(farmacia.GetAllModel());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona una farmacia");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        tblFarmacias.setModel(new Farmacia().GetAllModel());
        JOptionPane.showMessageDialog(rootPane, "Datos Actualizados");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        frmNMFarmacia obj = new frmNMFarmacia();
        obj.setTitle("Nueva Farmacia");
        obj.setModal(true);
        obj.setVisible(true);
        tblFarmacias.setModel(new Farmacia().GetAllModel());
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (tblFarmacias.getSelectedRow()>= 0) {
            int idFarmacia = (int) tblFarmacias.getValueAt(tblFarmacias.getSelectedRow(), 0);
            try{
            frmNMFarmacia obj = new frmNMFarmacia(idFarmacia);
            obj.setTitle("Modificar Farmacia");
            obj.setModal(true);
            obj.setVisible(true);
            tblFarmacias.setModel(new Farmacia().GetAllModel());
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecciona una farmacia");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblFarmaciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFarmaciasMouseClicked
        btnMostrarProductos.setVisible(true);
    }//GEN-LAST:event_tblFarmaciasMouseClicked

    private void btnMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductosActionPerformed
        frmProductos obj = new frmProductos((int)tblFarmacias.getValueAt(tblFarmacias.getSelectedRow(), 0));
        frmMain.desktopPane.add(obj);
        obj.toFront();
        obj.setVisible(true);
    }//GEN-LAST:event_btnMostrarProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarProductos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tblFarmacias;
    // End of variables declaration//GEN-END:variables
}
